use_frameworks!

platform :ios, '9.0'

target 'ComponentServicesDemo_Example' do
  pod 'ComponentServicesDemo', :path => '../'

  target 'ComponentServicesDemo_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
