use_frameworks!

platform :ios, '9.0'

use_modular_headers!

target 'OCSwiftComponentA_Example' do
  pod 'OCSwiftComponentA', :path => '../'

  target 'OCSwiftComponentA_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
    pod 'ComponentServicesDemo', :path => '../../ComponentServicesDemo'

  end
end

